export enum ActionTypes {
  ADD_INPUT = 'ADD_INPUT',
  BACK = 'BACK',
  CHANGE_URL = 'CHANGE_URL',
  CLOSE_MODAL = 'CLOSE_MODAL',
  GET_CAMPAIGN_REQUEST = 'GET_CAMPAIGN_REQUEST',
  GET_TARGETING_POTENTIAL_REQUEST = 'GET_TARGETING_POTENTIAL_REQUEST',
  HANDLE_OPTIONS = 'HANDLE_OPTIONS',
  OPEN_MODAL = 'OPEN_MODAL',
  REMOVE_INPUT = 'REMOVE_INPUT',
  RESET_CAMPAIGN_REQUEST = 'RESET_CAMPAIGN_REQUEST',
  RESTRICTED = 'RESTRICTED',
  SAVE_LOCATION = 'SAVE_LOCATION',
  UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN',
  UPDATE_CAMPAIGN_REQUEST = 'UPDATE_CAMPAIGN_REQUEST',
  UPDATE_TARGETING_POTENTIAL = 'UPDATE_TARGETING_POTENTIAL'
}
